# Generated by Django 5.0.1 on 2024-01-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapi', '0003_alter_waitlistentry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
