# Generated by Django 5.0.1 on 2024-01-11 21:25

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapi', '0004_alter_waitlistentry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
