# Generated by Django 5.0.1 on 2024-01-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlistapi', '0011_alter_waitlistentry_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistentry',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='LastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
